CREATE TABLE [ml].[Features](
	[titleid] [char](9) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[AvgRating] [decimal](4, 2) NULL,
	[Duration] [int] NULL,
	[StartYear] [smallint] NULL,
	[YearCode] [int] NOT NULL,
	[Western] [int] NULL,
	[War] [int] NULL,
	[Thriller] [int] NULL,
	[Talk-Show] [int] NULL,
	[Sport] [int] NULL,
	[Short] [int] NULL,
	[Sci-Fi] [int] NULL,
	[Romance] [int] NULL,
	[Reality-TV] [int] NULL,
	[News] [int] NULL,
	[Mystery] [int] NULL,
	[Musical] [int] NULL,
	[Music] [int] NULL,
	[Horror] [int] NULL,
	[History] [int] NULL,
	[Game-Show] [int] NULL,
	[Film-Noir] [int] NULL,
	[Fantasy] [int] NULL,
	[Family] [int] NULL,
	[Drama] [int] NULL,
	[Documentary] [int] NULL,
	[Crime] [int] NULL,
	[Comedy] [int] NULL,
	[Biography] [int] NULL,
	[Animation] [int] NULL,
	[Adventure] [int] NULL,
	[Adult] [int] NULL,
	[Action] [int] NULL
)